///*
// * This file was generated by the Gradle 'init' task.
// */
//

plugins {
    java
    id("org.springframework.boot") version "2.7.18"
    id("io.spring.dependency-management") version "1.0.15.RELEASE"
}

group = "com.example"
version = "0.0.1-SNAPSHOT"
description = "PlantUmlWebEditorV2"


java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}

repositories {
    mavenCentral()
}

extra["jjwtVersion"] = "0.11.5"
extra["plantumlVersion"] = "1.2023.7"
extra["lombokVersion"] = "1.18.30"

dependencies {
    // Spring Boot Starters
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-security")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-validation")

    // DevTools
    developmentOnly("org.springframework.boot:spring-boot-devtools")

    // Database
    runtimeOnly("org.postgresql:postgresql")

    // JWT
    implementation("io.jsonwebtoken:jjwt-api:${property("jjwtVersion")}")
    runtimeOnly("io.jsonwebtoken:jjwt-impl:${property("jjwtVersion")}")
    runtimeOnly("io.jsonwebtoken:jjwt-jackson:${property("jjwtVersion")}")

    // PlantUML
    implementation("net.sourceforge.plantuml:plantuml:${property("plantumlVersion")}")

    // Lombok
    val lombokDep = "org.projectlombok:lombok:${property("lombokVersion")}"
    compileOnly(lombokDep)
    annotationProcessor(lombokDep)
    testCompileOnly(lombokDep)
    testAnnotationProcessor(lombokDep)

    // Testing
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.springframework.security:spring-security-test")
    testRuntimeOnly("com.h2database:h2")
    testImplementation("org.junit.jupiter:junit-jupiter")
    testImplementation("org.junit.platform:junit-platform-suite")
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
    options.annotationProcessorPath = configurations.annotationProcessor.get()
}

tasks.withType<Test> {
    useJUnitPlatform()
}

tasks.withType<JavaCompile>().configureEach {
    options.compilerArgs.add("-parameters")
}

// Handle duplicates during JAR building
tasks.bootJar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    exclude("**/spring-boot-devtools-*.jar")
    exclude("META-INF/*.SF")
    exclude("META-INF/*.DSA")
    exclude("META-INF/*.RSA")
    archiveClassifier.set("")
}

tasks.jar {
    enabled = false
}